name: Live CI - Statameet 2021

on:
  push:
    branches: [ dev ]

jobs:
  deploy_live:
    # if: "!contains(github.event.head_commit.message, '[BOT]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.0
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --no-interaction

      - name: Deploy with Deployer
        uses: deployphp/action@master
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          dep: deploy staging -v
